version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    working_directory: ~/workflows_branch_filter
    steps:
      - checkout
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run:
          name: Run tests
          command: rake

  deploy:
    machine:
        enabled: true
    working_directory: ~/workflows_branch_filter
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: |
            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            EOF

            wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
            heroku git:remote -a $HEROKU_APP

      - run:
          command: |
            git push heroku master
            heroku run rake db:migrate
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
